Cliente/Models/CustomerOrder.cs
using System;
using System.Collections.Generic;

namespace Cliente.Models
{
    public partial class CustomerOrder
    {
        public CustomerOrder()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public DateTime Date { get; set; }
        public int OrderStatusId { get; set; }
        public decimal Amount { get; set; }

        public virtual Customer? Customer { get; set; } = null!;
        public virtual OrderStatus? OrderStatus { get; set; } = null!;
        public virtual ICollection<OrderDetail>? OrderDetail { get; set; }
    }
}

Cliente/Controllers/CustomerOrderController.cs
using Cliente.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

namespace Cliente.Controllers
{
    public class CustomerOrderController : Controller
    {
        private readonly string UrlCustomers;
        private readonly string UrlProducts;
        private readonly string UrlOrderStatuses;
        private readonly string UrlCustomerOrder;
        private readonly HttpClient client = new HttpClient();
        public CustomerOrderController(IConfiguration confi)
        {
            UrlCustomers = confi["EndPoint:UrlCustomers"];
            UrlProducts = confi["EndPoint:UrlProducts"];
            UrlOrderStatuses = confi["EndPoint:UrlOrderStatuses"];
            UrlCustomerOrder = confi["EndPoint:UrlCustomerOrders"];
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> NewOrder(int id)
        {
            CustomerOrderDTO dto = new CustomerOrderDTO();
            var urlID = UrlCustomers + "/" + id;
            var customer = JsonConvert.DeserializeObject<CustomerDTO>(await client.GetStringAsync(urlID));
            dto.Customer = customer;
            dto.CustomerId = customer.Id;
            var products = JsonConvert.DeserializeObject<List<ProductDTO>>(await client.GetStringAsync(UrlProducts));

            CustomerOrderDTO customerOrderDTO = new CustomerOrderDTO();
            customerOrderDTO.CustomerId = customer.Id;
            customerOrderDTO.OrderStatusId = 1;
            customerOrderDTO.Date = DateTime.Now;
            customerOrderDTO.Amount = 0;

            //var result = JsonConvert.DeserializeObject<CustomerOrderDTO>(await client.GetStringAsync(UrlCustomerOrder));



            ViewBag.Products = products.ConvertAll(p =>
            {
                return new SelectListItem()
                {
                    Text = p.Name,
                    Value = p.Id.ToString(),
                    Selected = false
                };
            });
            
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> NewOrder([FromBody] CustomerOrderDTO order)
        {
            var result = await client.PostAsJsonAsync(UrlCustomerOrder, order);

            if(result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> ObtenerPrecio([FromBody] int id)
        {
            var urlID = UrlProducts + "/" + id;
            var product = JsonConvert.DeserializeObject<ProductDTO>(await client.GetStringAsync(urlID));

            return Ok(product.UnitPrice);
        }

    }
}

Cliente/Views/CustomerOrder/NewOrder.cshtml
@model Cliente.DTOs.CustomerOrderDTO

@{
    ViewData["Title"] = "NewOrder";
}

@{
    List<SelectListItem> Productos = ViewBag.Products;
}

<h1>Nuevo Pedido</h1>


<div class="card">
    <div class="card-header">
        Pedido
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-sm-4">
                <label class="form-label" asp-for="CustomerId">Id Cliente</label>
                <input class="form-control form-control-sm" type="text" asp-for=CustomerId disabled="true" id="txtcliente">
            </div>
            
            <div class="col-sm-4">
                <label class="form-label" asp-for="Customer.FirstName">Nombre</label>
                <input class="form-control form-control-sm" type="text" asp-for=Customer.FirstName id="txtnombre">
            </div>
            <div class="col-sm-4">
                <label class="form-label">Apellido</label>
                <input class="form-control form-control-sm" asp-for="Customer.LastName" type="text" id="txtapellido">
            </div>
        </div>
        <hr />
        <div class="row align-items-end">
            <div class="col-sm-3">
                <label class="form-label">Producto</label>
                <select id="txtproducto" asp-items="@Productos" class="form-select"></select>
            </div>
            <div class="col-sm-3">
                <label class="form-label">Precio</label>
                <input class="form-control form-control-sm" type="text" id="txtprecio">
            </div>
            <div class="col-sm-3">
                <label class="form-label">Cantidad</label>
                <input class="form-control form-control-sm" type="text" id="txtcantidad">
            </div>
            <div class="col-sm-3">
                <button class="btn btn-success btn-sm" id="btnAgregar">Agregar</button>
                <button class="btn btn-primary btn-sm" id="btnTerminar">Cerrar Pedido</button>
            </div>
        </div>

        <hr />
       
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-sm" id="tbProducto">
                    <thead>
                        <tr class="table-dark">
                            <th>Codigo</th>
                            <th>Producto</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="4" class="text-end">Total General</th>
                            <th id="totalGeneral">0</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>


    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {

    <script>

        var totalGeneral = 0;

        $("#btnAgregar").on("click", function () {

            var precio = parseFloat($("#txtprecio").val());
            var cantidad = parseFloat($("#txtcantidad").val());
            var total = precio * cantidad;

            // Obtener el texto del producto seleccionado
            var productoSeleccionado = $("#txtproducto option:selected").text();
            var codigo = $("#txtproducto option:selected").val();

            $("#tbProducto tbody").append(
                $("<tr>").append(
                    $("<td>").text(codigo),
                    $("<td>").text(productoSeleccionado),
                    $("<td>").text(precio.toFixed(2)),
                    $("<td>").text(cantidad),
                    $("<td>").text(total.toFixed(2))
                )
            );

            totalGeneral += total;
            $("#totalGeneral").text(totalGeneral.toFixed(2));

            $("#txtproducto").val("")
            $("#txtprecio").val("")
            $("#txtcantidad").val("")
            $("#txtproducto").focus();
        })

        $("#btnTerminar").on("click", function () {

            var orderDetail = []
            var total = 0;

            $("#tbProducto > tbody > tr").each(function (i, tr) {

                orderDetail.push(
                    {
                        CustomerOrderId: '0',
                        ProductId: $(tr).find('td:eq(0)').text(),
                        Quantity: $(tr).find('td:eq(3)').text(),
                        Amount: $(tr).find('td:eq(2)').text()
                    }
                )

                total = total + parseFloat($(tr).find('td:eq(3)').text());
            })

            var customerOrder = {

                CustomerId: $("#txtcliente").val(),
                Amount: totalGeneral,
                OrderDetail: orderDetail
            }

            console.log(customerOrder);

            jQuery.ajax({
                url: '@Url.Action("NewOrder", "CustomerOrder")',
                type: "POST",
                data: JSON.stringify(customerOrder),
                datatype: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.respuesta) {
                        alert("Venta Registrada")

                        location.reload();
                    }

                }

            })
        })

        // Manejo del dropdown en cascada
        const urlObtenerPrecio = '@Url.Action("ObtenerPrecio")';
        $("#txtproducto").change(async function () {

            console.log("El select cambio");
            const valorSeleccionado = $(this).val();

            const respuesta = await fetch(urlObtenerPrecio, {
                method: 'POST',
                body: valorSeleccionado,
                headers: {
                    'Content-Type': 'application/json'
                }
            });

            const json = await respuesta.json();
            console.log(json);
            $("#txtprecio").val(json);

        })


    </script>
}